[project]
name = "game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Winston", email = "9567726+winstonleedev@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pygame-ce>=2.5.8",
    "pymunk>=7.3.0",
    "pyxel>=2.9.9",
]

[project.scripts]
game = "game:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
